Repository Yelp/swagger-gradle-codegen, pull requests merged in 2020-02, with the labels that each got.

#89 Remove samples/generated-code as it is duplicated by junit-tests
  README.md
  SAMPLES.md
  samples/generated-code/build.gradle
  samples/generated-code/simplified_pet_store.json
  samples/generated-code/src/main/AndroidManifest.xml
  samples/generated-code/src/main/java/com/yelp/codegen/generatecodesamples/apis/DefaultApi.kt
  samples/generated-code/src/main/java/com/yelp/codegen/generatecodesamples/models/Category.kt
  samples/generated-code/src/main/java/com/yelp/codegen/generatecodesamples/models/Pet.kt
  samples/generated-code/src/main/java/com/yelp/codegen/generatecodesamples/models/Tag.kt
  samples/generated-code/src/main/java/com/yelp/codegen/generatecodesamples/tools/CollectionFormatConverterFactory.kt
  samples/generated-code/src/main/java/com/yelp/codegen/generatecodesamples/tools/CollectionFormats.kt
  samples/generated-code/src/main/java/com/yelp/codegen/generatecodesamples/tools/EnumToValueConverterFactory.kt
  samples/generated-code/src/main/java/com/yelp/codegen/generatecodesamples/tools/GeneratedCodeConverters.kt
  samples/generated-code/src/main/java/com/yelp/codegen/generatecodesamples/tools/TypesAdapters.kt
  samples/generated-code/src/main/java/com/yelp/codegen/generatecodesamples/tools/WrapperConverterFactory.kt
  samples/generated-code/src/main/java/com/yelp/codegen/generatecodesamples/tools/XNullable.kt
  samples/generated-code/src/main/java/com/yelp/codegen/generatecodesamples/tools/XNullableAdapterFactory.kt
  samples/generated-code/src/main/java/swagger.json
  samples/generated-code/src/test/java/com/yelp/codegen/generatecodesamples/InvokeRetrofitTest.kt
  settings.gradle.kts
Labels: infra

#86 Pre commit hooks and Samples update
  .pre-commit-config.yaml
  .secrets.baseline
  .travis.yml
  Makefile
  plugin/src/main/java/com/yelp/codegen/Main.kt
  plugin/src/main/java/com/yelp/codegen/plugin/GenerateTask.kt
  plugin/src/main/java/com/yelp/codegen/plugin/GenerateTaskConfiguration.kt
  plugin/src/test/java/com/yelp/codegen/KotlinGeneratorTest.kt
  samples/junit-tests/.gitignore
  samples/junit-tests/src/main/java/com/yelp/codegen/generatecodesamples/tools/CollectionFormatConverterFactory.kt
  samples/junit-tests/src/main/java/com/yelp/codegen/generatecodesamples/tools/EnumToValueConverterFactory.kt
  samples/junit-tests/src/main/java/com/yelp/codegen/generatecodesamples/tools/TypesAdapters.kt
  samples/junit-tests/src/main/java/com/yelp/codegen/generatecodesamples/tools/WrapperConverterFactory.kt
  samples/junit-tests/src/test/java/com/yelp/codegen/generatecodesamples/FormatEndpointTest.kt
  samples/junit-tests/src/test/java/com/yelp/codegen/generatecodesamples/NestedAdditionalPropertiesCustomDescriptionTest.kt
  samples/junit-tests/src/test/java/com/yelp/codegen/generatecodesamples/NestedAdditionalPropertiesEndpointTest.kt
  samples/junit-tests/src/test/java/com/yelp/codegen/generatecodesamples/PropertyArrayEndpointTest.kt
  samples/junit-tests/src/test/java/com/yelp/codegen/generatecodesamples/PropertyMapEndpointTest.kt
  samples/junit-tests/src/test/java/com/yelp/codegen/generatecodesamples/TopLevelMapEndpointTest.kt
  samples/junit-tests/src/test/java/com/yelp/codegen/generatecodesamples/xnullable/XnullableNestedAdditionalPropertiesEndpointTest.kt
  samples/junit-tests/src/test/java/com/yelp/codegen/generatecodesamples/xnullable/XnullablePropertyArrayEndpointTest.kt
  samples/junit-tests/src/test/java/com/yelp/codegen/generatecodesamples/xnullable/XnullableRequiredPropertyArrayEndpointTest.kt
  samples/kotlin-coroutines/src/test/java/com/yelp/codegen/samples/kotlincoroutines/CoroutinesEndpointsTest.kt
  samples/kotlin-coroutines/src/test/java/com/yelp/codegen/samples/kotlincoroutines/tools/CoroutineDispatcherRule.kt
Labels: infra

#88 Annotate with @JsonClass classes with no parameters/variables
  plugin/src/main/java/com/yelp/codegen/KotlinGenerator.kt
  plugin/src/main/resources/kotlin/data_class.mustache
  plugin/src/test/java/com/yelp/codegen/KotlinGeneratorTest.kt
  samples/junit-tests/src/main/java/com/yelp/codegen/generatecodesamples/models/EmptyModel.kt
Labels: enhancement

#91 Bump io.swagger:swagger-codegen from 2.3.1 to 2.4.12
  plugin/build.gradle.kts
  plugin/src/main/java/com/yelp/codegen/SharedCodegen.kt
  plugin/src/main/java/com/yelp/codegen/utils/InlineModelResolver.java
  samples/junit-tests/junit_tests_specs.json
  samples/junit-tests/src/main/java/com/yelp/codegen/generatecodesamples/apis/ModelNameCheckApi.kt
  samples/junit-tests/src/main/java/com/yelp/codegen/generatecodesamples/models/InlineResponse200.kt
  samples/junit-tests/src/main/java/com/yelp/codegen/generatecodesamples/models/ModelWithOnlyTitle.kt
  samples/junit-tests/src/main/java/com/yelp/codegen/generatecodesamples/models/ModelWithOnlyXModel.kt
  samples/junit-tests/src/main/java/com/yelp/codegen/generatecodesamples/models/ModelWithXModelAndTitle.kt
  samples/junit-tests/src/main/java/swagger.json
  samples/junit-tests/src/test/java/com/yelp/codegen/generatecodesamples/ModelNameCheckEndpointTest.kt
Labels: enhancement

#92 Update make test to run pre-commit hooks on the whole codebase
  Makefile
Labels: infra

#93 Fix not formatted PluginTests
  plugin/src/test/java/com/yelp/plugin/PluginTests.kt
Labels: infra

#94 Cache pip and pre-commit folders
  .travis.yml
Labels: infra

#90 Update mustache style
  .pre-commit-config.yaml
  plugin/src/main/java/com/yelp/codegen/KotlinGenerator.kt
  plugin/src/main/java/com/yelp/codegen/SharedCodegen.kt
  plugin/src/main/java/com/yelp/codegen/utils/KotlinLangUtils.kt
  plugin/src/main/resources/kotlin/data_class.mustache
  plugin/src/main/resources/kotlin/data_class_opt_var.mustache
  plugin/src/main/resources/kotlin/data_class_req_var.mustache
  plugin/src/main/resources/kotlin/enum_class.mustache
  plugin/src/main/resources/kotlin/model.mustache
  plugin/src/main/resources/kotlin/retrofit2/api.mustache
  plugin/src/main/resources/kotlin/retrofit2/bodyParams.mustache
  plugin/src/main/resources/kotlin/retrofit2/formParams.mustache
  plugin/src/main/resources/kotlin/tools/CollectionFormatConverterFactory.kt.mustache
  plugin/src/main/resources/kotlin/tools/CollectionFormats.kt.mustache
  plugin/src/main/resources/kotlin/tools/EnumToValueConverterFactory.kt.mustache
  plugin/src/main/resources/kotlin/tools/GeneratedCodeConverters.kt.mustache
  plugin/src/main/resources/kotlin/tools/TypesAdapters.kt.mustache
  plugin/src/main/resources/kotlin/tools/WrapperConverterFactory.kt.mustache
  plugin/src/main/resources/kotlin/tools/XNullableAdapterFactory.kt.mustache
  plugin/src/main/resources/kotlin/type_alias.mustache
  samples/junit-tests/junit_tests_specs.json
  samples/junit-tests/src/main/java/com/yelp/codegen/generatecodesamples/apis/FileApi.kt
  samples/junit-tests/src/main/java/com/yelp/codegen/generatecodesamples/apis/ResourceApi.kt
  samples/junit-tests/src/main/java/com/yelp/codegen/generatecodesamples/apis/XnullableApi.kt
  samples/junit-tests/src/main/java/com/yelp/codegen/generatecodesamples/models/EmptyModel.kt
  samples/junit-tests/src/main/java/com/yelp/codegen/generatecodesamples/models/FormatResponses.kt
  samples/junit-tests/src/main/java/com/yelp/codegen/generatecodesamples/models/PropertyArray.kt
  samples/junit-tests/src/main/java/com/yelp/codegen/generatecodesamples/models/PropertyMap.kt
  samples/junit-tests/src/main/java/com/yelp/codegen/generatecodesamples/models/RequiredTypeResponses.kt
  samples/junit-tests/src/main/java/com/yelp/codegen/generatecodesamples/models/ReservedKeywords.kt
  samples/junit-tests/src/main/java/com/yelp/codegen/generatecodesamples/models/TopLevelEnum.kt
  samples/junit-tests/src/main/java/com/yelp/codegen/generatecodesamples/models/TypeResponses.kt
  samples/junit-tests/src/main/java/com/yelp/codegen/generatecodesamples/models/XnullableFormatResponses.kt
  samples/junit-tests/src/main/java/com/yelp/codegen/generatecodesamples/models/XnullablePropertyArray.kt
  samples/junit-tests/src/main/java/com/yelp/codegen/generatecodesamples/models/XnullablePropertyMap.kt
  samples/junit-tests/src/main/java/com/yelp/codegen/generatecodesamples/models/XnullableRequiredPropertyArray.kt
  samples/junit-tests/src/main/java/com/yelp/codegen/generatecodesamples/models/XnullableRequiredPropertyMap.kt
  samples/junit-tests/src/main/java/com/yelp/codegen/generatecodesamples/models/XnullableRequiredTypeResponses.kt
  samples/junit-tests/src/main/java/com/yelp/codegen/generatecodesamples/models/XnullableTypeResponses.kt
  samples/junit-tests/src/main/java/swagger.json
Labels: enhancement

#100 Regenerate samples
  samples/junit-tests/src/main/java/com/yelp/codegen/generatecodesamples/apis/ModelNameCheckApi.kt
  samples/junit-tests/src/main/java/com/yelp/codegen/generatecodesamples/models/InlineResponse200.kt
  samples/junit-tests/src/main/java/com/yelp/codegen/generatecodesamples/models/ModelWithOnlyTitle.kt
  samples/junit-tests/src/main/java/com/yelp/codegen/generatecodesamples/models/ModelWithOnlyXModel.kt
  samples/junit-tests/src/main/java/com/yelp/codegen/generatecodesamples/models/ModelWithXModelAndTitle.kt
  samples/junit-tests/src/main/java/swagger.json
Labels: infra

#101 File uploads tests
  plugin/src/main/java/com/yelp/codegen/SharedCodegen.kt
  plugin/src/main/resources/kotlin/retrofit2/api.mustache
  samples/junit-tests/junit_tests_specs.json
  samples/junit-tests/src/main/java/com/yelp/codegen/generatecodesamples/apis/FileApi.kt
  samples/junit-tests/src/main/java/swagger.json
  samples/junit-tests/src/test/java/com/yelp/codegen/generatecodesamples/PostFileEndpointTest.kt
  samples/junit-tests/src/test/java/com/yelp/codegen/generatecodesamples/tools/MultiPartTestUtil.kt
Labels: bug, enhancement

#119 Add Action to validate the Gradle Wrapper
  .github/workflows/gradle-wrapper-validation.yml
Labels: infra

#124 Setup Github Actions for preMerge
  .github/workflows/pre-merge.yaml
  .pre-commit-config.yaml
  build.gradle.kts
Labels: infra

#125 Remove Travis Config file
  .travis.yml
  README.md
Labels: infra
