Repository Yelp/swagger-gradle-codegen, pull requests merged in 2020-03, with the labels that each got.

#102 Add Gradle Lazy Configuration take n° 2
  README.md
  gradle-plugin/plugin/src/main/java/com/yelp/codegen/plugin/CodegenPlugin.kt
  gradle-plugin/plugin/src/main/java/com/yelp/codegen/plugin/FeatureConfiguration.kt
  gradle-plugin/plugin/src/main/java/com/yelp/codegen/plugin/GenerateTask.kt
  gradle-plugin/plugin/src/main/java/com/yelp/codegen/plugin/GenerateTaskConfiguration.kt
  gradle-plugin/plugin/src/main/java/com/yelp/codegen/plugin/VersionHelper.kt
  gradle-plugin/plugin/src/test/testProject/build.gradle.kts
  samples/groovy-android/build.gradle
  samples/kotlin-android-moshi-codegen/build.gradle.kts
  samples/kotlin-android/build.gradle.kts
Labels: enhancement

#127 Drop support for moshi-kotlin (reflective approach for JSON encoding/decoding)
  README.md
  gradle-plugin/plugin/src/main/resources/kotlin/tools/GeneratedCodeConverters.kt.mustache
  samples/groovy-android/build.gradle
  samples/junit-tests/build.gradle
  samples/junit-tests/src/main/java/com/yelp/codegen/generatecodesamples/tools/GeneratedCodeConverters.kt
  samples/kotlin-android-moshi-codegen/.gitignore
  samples/kotlin-android-moshi-codegen/build.gradle.kts
  samples/kotlin-android-moshi-codegen/moshi.pro
  samples/kotlin-android-moshi-codegen/src/main/AndroidManifest.xml
  samples/kotlin-android/build.gradle.kts
  samples/kotlin-coroutines/build.gradle
  settings.gradle.kts
Labels: breaking change ⚠️, enhancement

#96 Codecov fix
  .github/workflows/pre-merge.yaml
  gradle-plugin/plugin/build.gradle.kts
Labels: infra

#128 Update Gradle plugin-publish to 0.11.0
  gradle-plugin/plugin/build.gradle.kts
Labels: infra
